### ISSUE TITLE
Gigaword Query

### ISSUE THREAD

**Issue by ksuderman** [lapps/lapps.github.io#16]
All Solr Gigaword queries always return exactly 10 documents.  It looks trying to convert the $size parameter to an integer fails, in which case the default 10 is used.

**Comment by jdwright** [comment]
is this a problem on your end or my end?

**Comment by ksuderman** [comment]
I think this is a problem on my end parsing the input from the Galaxy UI.

**Comment by ksuderman** [comment]
Yep, it was a problem on my end.  A ClassCastException during parsing was being swallowed so it just took some time to determine what, exactly, was throwing the exception.  

This is fixed by https://github.com/lappsgrid-incubator/Galaxy/commit/59deb9ed69d5024134ec34e203a7935e953ddca5
