### ISSUE TITLE
New Services

### ISSUE THREAD

**Issue by ksuderman** [lapps/lapps.github.io#26]
New services to be installed into the Service Manager and Galaxy:

- [ ] Swirl http://surdeanu.info/mihai/swirl/
- [ ] Stanford relation extractor https://nlp.stanford.edu/software/relationExtractor.html
- [ ] Stanford Machine Learning https://nlp.stanford.edu/software/classifier.html

Once the projects have been started (i.e. have their own GitHub repository) they can be added to the Waffle board.

**Comment by keighrim** [comment]
Also, Stanford BioNLP https://nlp.stanford.edu/software/eventparser.shtml

**Comment by ksuderman** [comment]
See also the tools from https://www.ncbi.nlm.nih.gov/research/bionlp/Tools/

**Comment by keighrim** [comment]
split this issue to 
* lappsgrid-incubator/Services#21
* lappsgrid-incubator/Services#22
* lappsgrid-incubator/Services#23
* lappsgrid-incubator/Services#24
* lappsgrid-incubator/Services#25

Closing this one.
